[package]
name = "envoy-acme-dynmod"
version = "0.1.0"
edition = "2024"

[dependencies]
envoy-proxy-dynamic-modules-rust-sdk = { git = "https://github.com/envoyproxy/envoy", tag = "v1.39.0" }
dashmap = "6.2.1"
instant-acme = "0.8.5"
prost = "0.14.4"
prost-types = "0.14.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_valid = "2.0.3"
tokio = { version = "1.53.1", features = ["fs", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-stream = { version = "0.1.18", features = ["net"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
tracing = "0.1.44"
x509-parser = "0.18.1"

[features]
default = []
envoy_1_37 = []

[build-dependencies]
reqwest = { version = "0.12.24", default-features = false, features = ["blocking", "rustls-tls"] }
tonic-prost-build = "0.14.6"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = false

